#!/bin/bash

backlight="/sys/class/backlight/intel_backlight"

function percent() {
    inotifywait -m -e modify "${backlight}/brightness" | \
        while read file_path file_event file_name; do 
            brightness=$(cat "${backlight}/brightness")
            max_brightness=$(cat "${backlight}/max_brightness")
            echo $(( (100 * $brightness) / $max_brightness ))
        done
}

if [[ -n $1 && $1 == "percent" ]]; then
    percent
fi
