swaylock -enf \
	-i ~/.config/wallpapers/background.jpg \
	--indicator-idle-visible \
    --indicator-radius 100 \
    --indicator-thickness 14 \
	--inside-color 232634 \
	--inside-clear-color e5c890 \
	--inside-ver-color ef9f76 \
	--key-hl-color ef9f76 \
	--ring-color 8caaee	\
	--ring-clear-color ef9f76 \
	--ring-ver-color ef9f76 \
	--separator-color ef9f76 \
	--text-color 8caaee	\
	--text-clear-color 51576d \
	--text-ver-color 51576d \
	--clock
