#!/bin/bash

wlan0="/sys/class/net/wlan0"

function status() {
    echo $(cat ${wlan0}/operstate)
}

function icon() {
    local status=$(status) 

    if [[ $status == "up" ]]; then
        echo "󰤨"
    elif [[ $status == "down" ]]; then
        echo ""
    fi
}

if [[ -n $1 && $1 == "status" ]]; then
    echo $(status)
elif [[ -n $1 && $1 == "icon" ]]; then
    echo $(icon)
fi
