#!/bin/bash

backlight="/sys/class/backlight/intel_backlight"

function percent() {
    max_brightness=$(cat ${backlight}/max_brightness)
    brightness=$(cat ${backlight}/brightness)

    percentage=$(( (100 * $brightness) / $max_brightness ))
    echo $percentage
}

function icon() {
    local percent=$(percent)

    if (( $percent <= 25 )); then
        echo "󰃞"
    elif (( $percent <= 50 )); then
        echo "󰃝"
    elif (( $percent <= 75 )); then
        echo "󰃟"
    elif (( $percent <= 100 )); then
        echo "󰃠"
    fi
}

if [[ -n $1 && $1 == "percent" ]]; then
    echo $(percent)
elif [[ -n $1 && $1 == "icon" ]]; then
    echo $(icon)
fi
