#!/bin/bash

function get_source_id() {
    defaultSourceId=$(pactl --format=json list sources | \
                    jq ".[] | select(.name == \"$(pactl get-default-source)\") | 
                        .properties | 
                        .[\"object.id\"] | 
                        tonumber")

    echo $defaultSourceId
}

function muted() {
    echo $(pactl --format=json list sources | jq ".[] | select(.name == \"$(pactl get-default-source)\") | 
                                                      .mute")
}

function toggle_mute() {
    wpctl set-mute $(get_source_id) toggle
}

function icon() {
    local muted=$(muted)

    if [[ $muted == "true" ]]; then
        echo ""
    elif [[ $muted == "false" ]]; then
        echo ""
    fi
}

if [[ -n $1 && -n $2 && $1 == "mute" && $2 == "status" ]]; then
    echo $(muted)
elif [[ -n $1 && -n $2 && $1 == "mute" && $2 == "toggle" ]]; then
    echo $(toggle_mute)
elif [[ -n $1 && $1 == "icon" ]]; then
    echo $(icon)
fi
