#!/bin/bash

function get_sink_id() {
    defaultSinkId=$(pactl --format=json list sinks | \
                    jq ".[] | select(.name == \"$(pactl get-default-sink)\") | 
                        .properties | 
                        .[\"object.id\"] | 
                        tonumber")

    echo $defaultSinkId
}

function percent() {
    pactl subscribe | grep --line-buffered -E "^Event 'change' on sink #$(get_sink_id)" | \
    while read line; do
        
        local percent=$(wpctl get-volume $(get_sink_id) | awk '{ print $2 * 100 }')

        if [[ -n $1 && $1 == "capped" && $percent -gt 100 ]]; then
            echo "100"
        else
            echo $percent
        fi

    done
}

function mute_status() {
    pactl subscribe | grep --line-buffered -E "^Event 'change' on sink #$(get_sink_id)" | \
    while read line; do
        echo $(pactl --format=json list sinks | \ 
                     jq ".[] | select(.name == \"$(pactl get-default-sink)\") | 
                         .mute")
    done
}

function mute_toggle() {
    wpctl set-mute $(get_sink_id) toggle 
}

if [[ -n $1 && -z $2 && $1 == "percent" ]]; then
    percent
elif [[ -n $1 && -n $2 && $1 == "percent" && $2 == "capped" ]]; then
    percent capped
elif [[ -n $1 && -n $2 && $1 == "mute" && $2 == "status" ]]; then
    mute_status
elif [[ -n $1 && -n $2 && $1 == "mute" && $2 == "toggle" ]]; then
    mute_toggle
fi
