#!/bin/bash

readonly WORKSPACES_NUMBER=7

function get_active_workspace() {
    echo $(hyprctl activeworkspace -j | jq '.id')
}

function icon() {
    echo ""
}

if [[ -n $1 && $1 == "active" ]]; then
    echo $(get_active_workspace)
elif [[ -n $1 && $1 == "icon" ]]; then
    echo $(icon)
fi
