#!/bin/bash

root="/sys/class/power_supply"

energy_full() {

    total=0
    n=0

    for battery in $(ls $root | grep -E '^BAT[0-9]+$'); do
        let "n++"
        let "total += $(cat $root/$battery/energy_full)"
    done

    let "total /= n"    # Calculate mean
    echo $total
}

energy_now() {

    total=0
    n=0

    for battery in $(ls $root | grep -E '^BAT[0-9]+$'); do
        let "n++"
        let "total += $(cat $root/$battery/energy_now)"
    done

    let "total /= n"    # Calculate mean
    echo $total
}

percent() {

    full=$(energy_full)
    now=$(energy_now)

    let "percent = (now * 100) / full"
    echo $percent
}

function icon() {
    local percent=$(percent) 

    if [[ $percent -le 10 ]]; then
        echo "󰁺"
    elif [[ $percent -le 20 ]]; then
        echo "󰁻"
    elif [[ $percent -le 30 ]]; then
        echo "󰁼"
    elif [[ $percent -le 40 ]]; then
        echo "󰁽"
    elif [[ $percent -le 50 ]]; then
        echo "󰁾"
    elif [[ $percent -le 60 ]]; then
        echo "󰁿"
    elif [[ $percent -le 70 ]]; then
        echo "󰂀"
    elif [[ $percent -le 80 ]]; then
        echo "󰂁"
    elif [[ $percent -le 90 ]]; then
        echo "󰂂"
    elif [[ $percent -le 100 ]]; then
        echo "󰁹"
    fi
}

if [[ -n $1 && $1 == "percent" ]]; then
    echo $(percent)
elif [[ -n $1 && $1 == "icon" ]]; then
    echo $(icon)
fi
