#!/bin/bash

grace=5

if [[ -n $1 && $1 == "now" ]]; then
    grace=0
fi

swaylock -nf \
	-i ~/.config/wallpapers/wallpaper-4.png \
    --indicator-x-position 400 \
	--indicator-idle-visible \
    --indicator-radius 200 \
    --indicator-thickness 14 \
	--inside-color 00000000 \
	--inside-clear-color 00000000 \
    --inside-caps-lock-color 00000000 \
	--inside-ver-color 00000000 \
    --inside-wrong-color 00000000 \
	--key-hl-color 00000000 \
	--ring-color 00000000 \
	--ring-clear-color 00000000 \
    --ring-caps-lock-color 00000000 \
	--ring-ver-color 00000000 \
    --ring-wrong-color 00000000 \
	--separator-color 00000000 \
	--text-color 88c0d0ff \
	--text-clear-color 88c0d0ff \
    --text-caps-lock-color e78284ff \
	--text-ver-color 88c0d0ff \
    --text-wrong-color e78284ff \
	--clock \
    --grace $grace \
    --timestr %R \
    --datestr "%A %d %B %Y" \
    --fade-in 0.2 \
    --font-size 100 \
    --effect-blur 4x4
