#!/bin/bash

function active() {
    hyprctl activeworkspace -j | jq '.id'
    socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - |\
        stdbuf -o0 grep '^workspace>>' |\
        stdbuf -o0 awk -F '>>|,' '{print $2}'
}

if [[ -n $1 && $1 == "active" ]]; then
    active
fi
